services:
  db:
    image: postgres:16
    container_name: hospital-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gibson
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hospital_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
